#!/bin/bash
# $Id$

set -e

BASE_DIR=$(dirname $0)

echo -n >$BASE_DIR/messages.po

for file in $BASE_DIR/regextool/*.py $BASE_DIR/ui/*.ui; do
	case "$file" in
		*.py)
			language='Python'
			;;
		*.ui)
			language='Glade'
			;;
		*)
			echo "Error: unsupported extension for file $file"
			continue
			;;
	esac

	xgettext \
		--join-existing \
		--language=$language \
		--output=$BASE_DIR/messages.po \
		$file
done

for file in $BASE_DIR/po/*.po; do
	msgmerge --update --sort-output $file $BASE_DIR/messages.po
done

rm -f $BASE_DIR/messages.po

exit
