#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os

log = os.popen('git log --date=short --no-merges --pretty="%ad%x00%an%x00<%ae>%x00%s"')

last = None

changelog = open('CHANGELOG', 'w')

for line in log:
    date, author, mail, message = line.strip().split('\x00')

    if last != date:
        if last:
            changelog.write('\n')

        changelog.write('%s  %s  %s\n\n' % (date, author, mail))

        last = date

    changelog.write('\t* %s\n' % message)

changelog.close()

log.close()
